### ISSUE TITLE
v4 broken on st3

### ISSUE THREAD

**Issue by krishantaylor** [frankyonnetti/gravity-sublime-theme#66]
Love this theme, but my syntax highlighting is slightly broken after the recent update. Here's what I see in the console:
```
Unable to parse color value ABB2BF at Packages/User/Color Highlighter/themes/One Dark Gravity.tmTheme:unknown
Unable to parse color value var(yellow3) at Packages/Theme - Gravity/One Dark Gravity.sublime-color-scheme:180:27
Unable to parse color value color(var(purple) alpha(0.63)) at Packages/Theme - Gravity/One Dark Gravity.sublime-color-scheme:279:27
```
I'm running sublime v3.2.2, build 3211.

**Comment by frankyonnetti** [comment]
Hi @krishantaylor 
I just posted a fix for the 2nd and 3rd error to (tag) version 4.0.1. Give **package control** time to update (should be less than an hour).

The 1st error is because the file has been removed (by me). You'll need to reset the color scheme in prefs if that comes up again.

Thanks!!
